### ISSUE TITLE
Days not progressing when on a server

### ISSUE THREAD

**Issue by om2j** [shudnal/Seasons#16]
Hi! Thank you for this mod.

When on a server, the days don't progress and the timer resets throughout the night whether I sleep or not.
This happens to me only on a dedicated server but everything works fine in solo. 
(I'm not using the realtime seasons)

**Comment by shudnal** [comment]
I'm aware of some sync issues. It will most likely be fixed in the next version.

**Comment by shudnal** [comment]
Pls check 1.2.6 version.

**Comment by om2j** [comment]
I checked the update, and the problem remains, unfortunately.

**Comment by shudnal** [comment]
Do you have any errors in log file? Maybe server config has "Change season only after sleep" enabled.
You say you've tried both waiting, sleeping and using skiptime command while connected to the server and you are stuck on last day of the season no matter what?

**Comment by shudnal** [comment]
I've just rechecked it on my server and singleplayer.
"Change season only after sleep" disabled - season changed.
"Change season only after sleep" enabled - sleeping - season changed.
"Change season only after sleep" enabled - not sleeping - season wasn't changed, day stucked at final day.

Everything is working as intended. Maybe you have some error in log file from other mod that prevents Seasons logic.
